name: IndexNow

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-and-submit:
    runs-on: ubuntu-latest

    steps:
      - name: Run IndexNow
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://kappalib.ru/sitemap.xml"
          key: ${{ secrets.INDEX_NOW_KEY }}
